//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     MicrosoftTeamsDemo
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MicrosoftTeamsDemo;

namespace MicrosoftTeamsDemo.cardSrcCable
{

    /// <summary>
    /// cardSrcCable
    /// </summary>
    public partial interface IcardSrcCable 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event cblGuide.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> cblGuide_PressEvent;

        /// <summary>
        /// Event cblPlay.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> cblPlay_PressEvent;

        /// <summary>
        /// Event navReturn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> navReturn_PressEvent;

        /// <summary>
        /// cblGuide.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void cblGuide_Selected(cardSrcCableBoolInputSigDelegate callback);

        /// <summary>
        /// cblGuide.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void cblGuide_Selected(bool digital);

        /// <summary>
        /// cblPlay.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void cblPlay_Selected(cardSrcCableBoolInputSigDelegate callback);

        /// <summary>
        /// cblPlay.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void cblPlay_Selected(bool digital);

        /// <summary>
        /// navReturn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void navReturn_Selected(cardSrcCableBoolInputSigDelegate callback);

        /// <summary>
        /// navReturn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void navReturn_Selected(bool digital);

        /// <summary>
        /// cblGuide.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void cblGuide_IndirectRichText(cardSrcCableStringInputSigDelegate callback);

        /// <summary>
        /// cblGuide.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void cblGuide_IndirectRichText(string serial);

        /// <summary>
        /// cblGuide.Icon Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void cblGuide_Icon(cardSrcCableStringInputSigDelegate callback);

        /// <summary>
        /// cblGuide.Icon Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void cblGuide_Icon(string serial);

        /// <summary>
        /// cblBack.Icon URL Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void cblBack_IconURL(cardSrcCableStringInputSigDelegate callback);

        /// <summary>
        /// cblBack.Icon URL Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void cblBack_IconURL(string serial);

        /// <summary>
        /// cblPlay.Icon URL Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void cblPlay_IconURL(cardSrcCableStringInputSigDelegate callback);

        /// <summary>
        /// cblPlay.Icon URL Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void cblPlay_IconURL(string serial);

        /// <summary>
        /// ComplexComponent cblDpad
        /// </summary>
        MicrosoftTeamsDemo.cardSrcCable.IcblDpad cblDpad { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="cardsrccable">The <see cref="IcardSrcCable"/> on which to apply the feedback.</param>
    public delegate void cardSrcCableBoolInputSigDelegate(BoolInputSig boolInputSig, IcardSrcCable cardsrccable);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="cardsrccable">The <see cref="IcardSrcCable"/> on which to apply the feedback.</param>
    public delegate void cardSrcCableStringInputSigDelegate(StringInputSig stringInputSig, IcardSrcCable cardsrccable);

    /// <summary>
    /// cardSrcCable
    /// </summary>
    internal partial class cardSrcCable : IcardSrcCable, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: cardSrcCable.cblGuide.Press
                /// cblGuide.Press
                /// </summary>
                public const uint cblGuide_PressEvent = 3;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: cardSrcCable.cblPlay.Press
                /// cblPlay.Press
                /// </summary>
                public const uint cblPlay_PressEvent = 4;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: cardSrcCable.navReturn.Press
                /// navReturn.Press
                /// </summary>
                public const uint navReturn_PressEvent = 5;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: cardSrcCable.cblGuide.Selected
                /// cblGuide.Selected
                /// </summary>
                public const uint cblGuide_SelectedState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: cardSrcCable.cblPlay.Selected
                /// cblPlay.Selected
                /// </summary>
                public const uint cblPlay_SelectedState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: cardSrcCable.navReturn.Selected
                /// navReturn.Selected
                /// </summary>
                public const uint navReturn_SelectedState = 5;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: cardSrcCable.cblGuide.IndirectRichText
                /// cblGuide.Indirect Rich Text
                /// </summary>
                public const uint cblGuide_IndirectRichTextState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: cardSrcCable.cblGuide.Icon
                /// cblGuide.Icon
                /// </summary>
                public const uint cblGuide_IconState = 2;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: cardSrcCable.cblBack.IconURL
                /// cblBack.Icon URL
                /// </summary>
                public const uint cblBack_IconURLState = 6;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: cardSrcCable.cblPlay.IconURL
                /// cblPlay.Icon URL
                /// </summary>
                public const uint cblPlay_IconURLState = 7;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="cardSrcCable"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal cardSrcCable(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="cardSrcCable"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal cardSrcCable(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="cardSrcCable"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 

            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.cblGuide_PressEvent, oncblGuide_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.cblPlay_PressEvent, oncblPlay_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.navReturn_PressEvent, onnavReturn_Press);
            cblDpad = new MicrosoftTeamsDemo.cardSrcCable.cblDpad(ComponentMediator, 35);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MicrosoftTeamsDemo.cardSrcCable.cblDpad)cblDpad).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MicrosoftTeamsDemo.cardSrcCable.cblDpad)cblDpad).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> cblGuide_PressEvent;
        private void oncblGuide_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = cblGuide_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> cblPlay_PressEvent;
        private void oncblPlay_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = cblPlay_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> navReturn_PressEvent;
        private void onnavReturn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = navReturn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void cblGuide_Selected(cardSrcCableBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.cblGuide_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void cblGuide_Selected(bool digital)
        {
            cblGuide_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void cblPlay_Selected(cardSrcCableBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.cblPlay_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void cblPlay_Selected(bool digital)
        {
            cblPlay_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void navReturn_Selected(cardSrcCableBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.navReturn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void navReturn_Selected(bool digital)
        {
            navReturn_Selected((sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void cblBack_IconURL(cardSrcCableStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.cblBack_IconURLState], this);
            }
        }

        /// <inheritdoc/>
        public void cblBack_IconURL(string serial)
        {
            cblBack_IconURL((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void cblGuide_Icon(cardSrcCableStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.cblGuide_IconState], this);
            }
        }

        /// <inheritdoc/>
        public void cblGuide_Icon(string serial)
        {
            cblGuide_Icon((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void cblGuide_IndirectRichText(cardSrcCableStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.cblGuide_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void cblGuide_IndirectRichText(string serial)
        {
            cblGuide_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void cblPlay_IconURL(cardSrcCableStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.cblPlay_IconURLState], this);
            }
        }

        /// <inheritdoc/>
        public void cblPlay_IconURL(string serial)
        {
            cblPlay_IconURL((sig, component) => sig.StringValue = serial);
        }

        /// <summary>
        /// ComplexComponent cblDpad
        /// </summary>
        public MicrosoftTeamsDemo.cardSrcCable.IcblDpad cblDpad { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "cardSrcCable", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            cblGuide_PressEvent = null;
            cblPlay_PressEvent = null;
            navReturn_PressEvent = null;
        }

        #endregion
    }
}
