//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     MicrosoftTeamsDemo
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MicrosoftTeamsDemo;

namespace MicrosoftTeamsDemo.widgetActivitiesMenu
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IactItemListByItem
    {

        /// <summary>
        /// Event widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<ItemEventArgs> actItemBtn_PressEvent;

        /// <summary>
        /// actItemList.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Visible(ushort listItemIndex, actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// Helper actItemList.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Visible(ushort listItemIndex, bool digital);

        /// <summary>
        /// actItemList.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Enable(ushort listItemIndex, actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// Helper actItemList.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Enable(ushort listItemIndex, bool digital);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemBtn_Selected(ushort itemIndex, actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="digital">The bool value to send to the panel.</param>
        void actItemBtn_Selected(ushort itemIndex, bool digital);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void actItemLabel_Indirect(ushort itemIndex, actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void actItemLabel_Indirect(ushort itemIndex, string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void actItemBtn_IconURL(ushort itemIndex, actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void actItemBtn_IconURL(ushort itemIndex, string serial);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class actItemList
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public event EventHandler<ItemEventArgs> actItemBtn_PressEvent;
        private void onactItemBtn_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<ItemEventArgs> handler = actItemBtn_PressEvent;
            if (handler != null)
                handler(this, new ItemEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.ItemIndex));
        }

        /// <inheritdoc/>
        public void actItemBtn_Selected(ushort itemIndex, actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_0__actItemBtn_SelectedState + (uint) itemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void actItemBtn_Selected(ushort itemIndex, bool digital)
        {
            actItemBtn_Selected(itemIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item1_VisibleState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, bool digital)
        {
            List_Item_Visible(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void List_Item_Enable(ushort listItemIndex, actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item1_EnableState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Enable(ushort listItemIndex, bool digital)
        {
            List_Item_Enable(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void actItemLabel_Indirect(ushort itemIndex, actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_0__actItemLabel_IndirectState + (uint) itemIndex * 1], this);
            }
        }

        /// <inheritdoc/>
        public void actItemLabel_Indirect(ushort itemIndex, string serial)
        {
            actItemLabel_Indirect(itemIndex, (sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void actItemBtn_IconURL(ushort itemIndex, actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_0__actItemBtn_IconURLState + (uint) itemIndex * 1], this);
            }
        }

        /// <inheritdoc/>
        public void actItemBtn_IconURL(ushort itemIndex, string serial)
        {
            actItemBtn_IconURL(itemIndex, (sig, component) => sig.StringValue = serial);
        }

        #endregion
    }

    /// <summary>
    /// actItemList
    /// </summary>
    public partial interface IactItemList : IactItemListByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_0__actItemBtn_PressEvent;

        /// <summary>
        /// Event widgetActivitiesMenu.actItemList.Items[1].actItemBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_1__actItemBtn_PressEvent;

        /// <summary>
        /// Event widgetActivitiesMenu.actItemList.Items[2].actItemBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_2__actItemBtn_PressEvent;

        /// <summary>
        /// Event widgetActivitiesMenu.actItemList.Items[3].actItemBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_3__actItemBtn_PressEvent;

        /// <summary>
        /// Event widgetActivitiesMenu.actItemList.Items[4].actItemBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_4__actItemBtn_PressEvent;

        /// <summary>
        /// Event widgetActivitiesMenu.actItemList.Items[5].actItemBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_5__actItemBtn_PressEvent;

        /// <summary>
        /// actItemList.List Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Visible(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Visible(bool digital);

        /// <summary>
        /// actItemList.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item1_Visible(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item1_Visible(bool digital);

        /// <summary>
        /// actItemList.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item2_Visible(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item2_Visible(bool digital);

        /// <summary>
        /// actItemList.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item3_Visible(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item3_Visible(bool digital);

        /// <summary>
        /// actItemList.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item4_Visible(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item4_Visible(bool digital);

        /// <summary>
        /// actItemList.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item5_Visible(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item5_Visible(bool digital);

        /// <summary>
        /// actItemList.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item6_Visible(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item6_Visible(bool digital);

        /// <summary>
        /// actItemList.List Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Enable(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Enable(bool digital);

        /// <summary>
        /// actItemList.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item1_Enable(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item1_Enable(bool digital);

        /// <summary>
        /// actItemList.List_Item2_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item2_Enable(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item2_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item2_Enable(bool digital);

        /// <summary>
        /// actItemList.List_Item3_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item3_Enable(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item3_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item3_Enable(bool digital);

        /// <summary>
        /// actItemList.List_Item4_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item4_Enable(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item4_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item4_Enable(bool digital);

        /// <summary>
        /// actItemList.List_Item5_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item5_Enable(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item5_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item5_Enable(bool digital);

        /// <summary>
        /// actItemList.List_Item6_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void actItemList_List_Item6_Enable(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// actItemList.List_Item6_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void actItemList_List_Item6_Enable(bool digital);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_0__actItemBtn_Selected(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_0__actItemBtn_Selected(bool digital);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[1].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_1__actItemBtn_Selected(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[1].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_1__actItemBtn_Selected(bool digital);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[2].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_2__actItemBtn_Selected(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[2].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_2__actItemBtn_Selected(bool digital);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[3].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_3__actItemBtn_Selected(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[3].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_3__actItemBtn_Selected(bool digital);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[4].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_4__actItemBtn_Selected(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[4].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_4__actItemBtn_Selected(bool digital);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[5].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_5__actItemBtn_Selected(actItemListBoolInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[5].actItemBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_5__actItemBtn_Selected(bool digital);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_0__actItemLabel_Indirect(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_0__actItemLabel_Indirect(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[1].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_1__actItemLabel_Indirect(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[1].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_1__actItemLabel_Indirect(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[2].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_2__actItemLabel_Indirect(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[2].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_2__actItemLabel_Indirect(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[3].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_3__actItemLabel_Indirect(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[3].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_3__actItemLabel_Indirect(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[4].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_4__actItemLabel_Indirect(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[4].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_4__actItemLabel_Indirect(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[5].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_5__actItemLabel_Indirect(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[5].actItemLabel.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_5__actItemLabel_Indirect(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_0__actItemBtn_IconURL(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_0__actItemBtn_IconURL(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[1].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_1__actItemBtn_IconURL(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[1].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_1__actItemBtn_IconURL(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[2].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_2__actItemBtn_IconURL(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[2].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_2__actItemBtn_IconURL(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[3].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_3__actItemBtn_IconURL(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[3].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_3__actItemBtn_IconURL(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[4].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_4__actItemBtn_IconURL(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[4].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_4__actItemBtn_IconURL(string serial);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[5].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_5__actItemBtn_IconURL(actItemListStringInputSigDelegate callback);

        /// <summary>
        /// widgetActivitiesMenu.actItemList.Items[5].actItemBtn.Icon URL Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_5__actItemBtn_IconURL(string serial);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="actitemlist">The <see cref="IactItemList"/> on which to apply the feedback.</param>
    public delegate void actItemListBoolInputSigDelegate(BoolInputSig boolInputSig, IactItemList actitemlist);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="actitemlist">The <see cref="IactItemList"/> on which to apply the feedback.</param>
    public delegate void actItemListStringInputSigDelegate(StringInputSig stringInputSig, IactItemList actitemlist);

    /// <summary>
    /// actItemList
    /// </summary>
    internal partial class actItemList : IactItemList, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion
        /// <summary>
        /// Number of Items.
        /// </summary>
        public uint ItemCount { get; private set; }

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: widgetActivitiesMenu.actItemList.Items[0].listItem_activityCONTRACT.actItemBtn.Press
                /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Press
                /// </summary>
                public const uint Items_0__actItemBtn_PressEvent = 1;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: widgetActivitiesMenu.actItemList.Items[1].listItem_activityCONTRACT.actItemBtn.Press
                /// widgetActivitiesMenu.actItemList.Items[1].actItemBtn.Press
                /// </summary>
                public const uint Items_1__actItemBtn_PressEvent = 2;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: widgetActivitiesMenu.actItemList.Items[2].listItem_activityCONTRACT.actItemBtn.Press
                /// widgetActivitiesMenu.actItemList.Items[2].actItemBtn.Press
                /// </summary>
                public const uint Items_2__actItemBtn_PressEvent = 3;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: widgetActivitiesMenu.actItemList.Items[3].listItem_activityCONTRACT.actItemBtn.Press
                /// widgetActivitiesMenu.actItemList.Items[3].actItemBtn.Press
                /// </summary>
                public const uint Items_3__actItemBtn_PressEvent = 4;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: widgetActivitiesMenu.actItemList.Items[4].listItem_activityCONTRACT.actItemBtn.Press
                /// widgetActivitiesMenu.actItemList.Items[4].actItemBtn.Press
                /// </summary>
                public const uint Items_4__actItemBtn_PressEvent = 5;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: widgetActivitiesMenu.actItemList.Items[5].listItem_activityCONTRACT.actItemBtn.Press
                /// widgetActivitiesMenu.actItemList.Items[5].actItemBtn.Press
                /// </summary>
                public const uint Items_5__actItemBtn_PressEvent = 6;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Visible
                /// actItemList.List Visibility
                /// </summary>
                public const uint actItemList_List_VisibleState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item1_Visible
                /// actItemList.List_Item1_Visible
                /// </summary>
                public const uint actItemList_List_Item1_VisibleState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item2_Visible
                /// actItemList.List_Item2_Visible
                /// </summary>
                public const uint actItemList_List_Item2_VisibleState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item3_Visible
                /// actItemList.List_Item3_Visible
                /// </summary>
                public const uint actItemList_List_Item3_VisibleState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item4_Visible
                /// actItemList.List_Item4_Visible
                /// </summary>
                public const uint actItemList_List_Item4_VisibleState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item5_Visible
                /// actItemList.List_Item5_Visible
                /// </summary>
                public const uint actItemList_List_Item5_VisibleState = 6;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item6_Visible
                /// actItemList.List_Item6_Visible
                /// </summary>
                public const uint actItemList_List_Item6_VisibleState = 7;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Enable
                /// actItemList.List Enable
                /// </summary>
                public const uint actItemList_List_EnableState = 8;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item1_Enable
                /// actItemList.List_Item1_Enable
                /// </summary>
                public const uint actItemList_List_Item1_EnableState = 9;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item2_Enable
                /// actItemList.List_Item2_Enable
                /// </summary>
                public const uint actItemList_List_Item2_EnableState = 10;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item3_Enable
                /// actItemList.List_Item3_Enable
                /// </summary>
                public const uint actItemList_List_Item3_EnableState = 11;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item4_Enable
                /// actItemList.List_Item4_Enable
                /// </summary>
                public const uint actItemList_List_Item4_EnableState = 12;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item5_Enable
                /// actItemList.List_Item5_Enable
                /// </summary>
                public const uint actItemList_List_Item5_EnableState = 13;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.List_Item6_Enable
                /// actItemList.List_Item6_Enable
                /// </summary>
                public const uint actItemList_List_Item6_EnableState = 14;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[0].listItem_activityCONTRACT.actItemBtn.Selected
                /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Selected
                /// </summary>
                public const uint Items_0__actItemBtn_SelectedState = 15;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[1].listItem_activityCONTRACT.actItemBtn.Selected
                /// widgetActivitiesMenu.actItemList.Items[1].actItemBtn.Selected
                /// </summary>
                public const uint Items_1__actItemBtn_SelectedState = 16;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[2].listItem_activityCONTRACT.actItemBtn.Selected
                /// widgetActivitiesMenu.actItemList.Items[2].actItemBtn.Selected
                /// </summary>
                public const uint Items_2__actItemBtn_SelectedState = 17;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[3].listItem_activityCONTRACT.actItemBtn.Selected
                /// widgetActivitiesMenu.actItemList.Items[3].actItemBtn.Selected
                /// </summary>
                public const uint Items_3__actItemBtn_SelectedState = 18;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[4].listItem_activityCONTRACT.actItemBtn.Selected
                /// widgetActivitiesMenu.actItemList.Items[4].actItemBtn.Selected
                /// </summary>
                public const uint Items_4__actItemBtn_SelectedState = 19;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[5].listItem_activityCONTRACT.actItemBtn.Selected
                /// widgetActivitiesMenu.actItemList.Items[5].actItemBtn.Selected
                /// </summary>
                public const uint Items_5__actItemBtn_SelectedState = 20;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[0].listItem_activityCONTRACT.actItemLabel.Indirect
                /// widgetActivitiesMenu.actItemList.Items[0].actItemLabel.Indirect
                /// </summary>
                public const uint Items_0__actItemLabel_IndirectState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[1].listItem_activityCONTRACT.actItemLabel.Indirect
                /// widgetActivitiesMenu.actItemList.Items[1].actItemLabel.Indirect
                /// </summary>
                public const uint Items_1__actItemLabel_IndirectState = 2;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[2].listItem_activityCONTRACT.actItemLabel.Indirect
                /// widgetActivitiesMenu.actItemList.Items[2].actItemLabel.Indirect
                /// </summary>
                public const uint Items_2__actItemLabel_IndirectState = 3;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[3].listItem_activityCONTRACT.actItemLabel.Indirect
                /// widgetActivitiesMenu.actItemList.Items[3].actItemLabel.Indirect
                /// </summary>
                public const uint Items_3__actItemLabel_IndirectState = 4;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[4].listItem_activityCONTRACT.actItemLabel.Indirect
                /// widgetActivitiesMenu.actItemList.Items[4].actItemLabel.Indirect
                /// </summary>
                public const uint Items_4__actItemLabel_IndirectState = 5;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[5].listItem_activityCONTRACT.actItemLabel.Indirect
                /// widgetActivitiesMenu.actItemList.Items[5].actItemLabel.Indirect
                /// </summary>
                public const uint Items_5__actItemLabel_IndirectState = 6;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[0].listItem_activityCONTRACT.actItemBtn.IconURL
                /// widgetActivitiesMenu.actItemList.Items[0].actItemBtn.Icon URL
                /// </summary>
                public const uint Items_0__actItemBtn_IconURLState = 2407;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[1].listItem_activityCONTRACT.actItemBtn.IconURL
                /// widgetActivitiesMenu.actItemList.Items[1].actItemBtn.Icon URL
                /// </summary>
                public const uint Items_1__actItemBtn_IconURLState = 2408;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[2].listItem_activityCONTRACT.actItemBtn.IconURL
                /// widgetActivitiesMenu.actItemList.Items[2].actItemBtn.Icon URL
                /// </summary>
                public const uint Items_2__actItemBtn_IconURLState = 2409;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[3].listItem_activityCONTRACT.actItemBtn.IconURL
                /// widgetActivitiesMenu.actItemList.Items[3].actItemBtn.Icon URL
                /// </summary>
                public const uint Items_3__actItemBtn_IconURLState = 2410;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[4].listItem_activityCONTRACT.actItemBtn.IconURL
                /// widgetActivitiesMenu.actItemList.Items[4].actItemBtn.Icon URL
                /// </summary>
                public const uint Items_4__actItemBtn_IconURLState = 2411;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetActivitiesMenu.actItemList.Items[5].listItem_activityCONTRACT.actItemBtn.IconURL
                /// widgetActivitiesMenu.actItemList.Items[5].actItemBtn.Icon URL
                /// </summary>
                public const uint Items_5__actItemBtn_IconURLState = 2412;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="actItemList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal actItemList(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="actItemList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal actItemList(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="actItemList"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_0__actItemBtn_PressEvent.ToString(), new Indexes(0, (ushort)Joins.Booleans.Items_0__actItemBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_1__actItemBtn_PressEvent.ToString(), new Indexes(1, (ushort)Joins.Booleans.Items_0__actItemBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_2__actItemBtn_PressEvent.ToString(), new Indexes(2, (ushort)Joins.Booleans.Items_0__actItemBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_3__actItemBtn_PressEvent.ToString(), new Indexes(3, (ushort)Joins.Booleans.Items_0__actItemBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_4__actItemBtn_PressEvent.ToString(), new Indexes(4, (ushort)Joins.Booleans.Items_0__actItemBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_5__actItemBtn_PressEvent.ToString(), new Indexes(5, (ushort)Joins.Booleans.Items_0__actItemBtn_PressEvent, false));

            ComponentMediator.ConfigureBooleanItemEvent(controlJoinId, Joins.Booleans.Items_0__actItemBtn_PressEvent, GetIndexes, onactItemBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_0__actItemBtn_PressEvent, onItems_0__actItemBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_1__actItemBtn_PressEvent, onItems_1__actItemBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_2__actItemBtn_PressEvent, onItems_2__actItemBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_3__actItemBtn_PressEvent, onItems_3__actItemBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_4__actItemBtn_PressEvent, onItems_4__actItemBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_5__actItemBtn_PressEvent, onItems_5__actItemBtn_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            Indexes indexes;
            if (_indexLookup.TryGetValue(eSigType.ToString() + join.ToString(), out indexes))
            {
                return new Indexes(indexes.ItemIndex, (ushort) (join - indexes.JoinIndex), false);
            }

            return new Indexes(0, 0, true);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_0__actItemBtn_PressEvent;
        private void onItems_0__actItemBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_0__actItemBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_1__actItemBtn_PressEvent;
        private void onItems_1__actItemBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_1__actItemBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_2__actItemBtn_PressEvent;
        private void onItems_2__actItemBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_2__actItemBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_3__actItemBtn_PressEvent;
        private void onItems_3__actItemBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_3__actItemBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_4__actItemBtn_PressEvent;
        private void onItems_4__actItemBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_4__actItemBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_5__actItemBtn_PressEvent;
        private void onItems_5__actItemBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_5__actItemBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void Items_0__actItemBtn_Selected(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_0__actItemBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_0__actItemBtn_Selected(bool digital)
        {
            Items_0__actItemBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_1__actItemBtn_Selected(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_1__actItemBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_1__actItemBtn_Selected(bool digital)
        {
            Items_1__actItemBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_2__actItemBtn_Selected(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_2__actItemBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_2__actItemBtn_Selected(bool digital)
        {
            Items_2__actItemBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_3__actItemBtn_Selected(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_3__actItemBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_3__actItemBtn_Selected(bool digital)
        {
            Items_3__actItemBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_4__actItemBtn_Selected(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_4__actItemBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_4__actItemBtn_Selected(bool digital)
        {
            Items_4__actItemBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_5__actItemBtn_Selected(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_5__actItemBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_5__actItemBtn_Selected(bool digital)
        {
            Items_5__actItemBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Enable(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Enable(bool digital)
        {
            actItemList_List_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item1_Enable(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item1_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item1_Enable(bool digital)
        {
            actItemList_List_Item1_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item1_Visible(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item1_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item1_Visible(bool digital)
        {
            actItemList_List_Item1_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item2_Enable(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item2_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item2_Enable(bool digital)
        {
            actItemList_List_Item2_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item2_Visible(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item2_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item2_Visible(bool digital)
        {
            actItemList_List_Item2_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item3_Enable(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item3_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item3_Enable(bool digital)
        {
            actItemList_List_Item3_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item3_Visible(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item3_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item3_Visible(bool digital)
        {
            actItemList_List_Item3_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item4_Enable(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item4_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item4_Enable(bool digital)
        {
            actItemList_List_Item4_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item4_Visible(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item4_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item4_Visible(bool digital)
        {
            actItemList_List_Item4_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item5_Enable(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item5_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item5_Enable(bool digital)
        {
            actItemList_List_Item5_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item5_Visible(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item5_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item5_Visible(bool digital)
        {
            actItemList_List_Item5_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item6_Enable(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item6_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item6_Enable(bool digital)
        {
            actItemList_List_Item6_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Item6_Visible(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_Item6_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Item6_Visible(bool digital)
        {
            actItemList_List_Item6_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void actItemList_List_Visible(actItemListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.actItemList_List_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void actItemList_List_Visible(bool digital)
        {
            actItemList_List_Visible((sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void Items_0__actItemBtn_IconURL(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_0__actItemBtn_IconURLState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_0__actItemBtn_IconURL(string serial)
        {
            Items_0__actItemBtn_IconURL((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_1__actItemBtn_IconURL(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_1__actItemBtn_IconURLState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_1__actItemBtn_IconURL(string serial)
        {
            Items_1__actItemBtn_IconURL((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_2__actItemBtn_IconURL(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_2__actItemBtn_IconURLState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_2__actItemBtn_IconURL(string serial)
        {
            Items_2__actItemBtn_IconURL((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_3__actItemBtn_IconURL(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_3__actItemBtn_IconURLState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_3__actItemBtn_IconURL(string serial)
        {
            Items_3__actItemBtn_IconURL((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_4__actItemBtn_IconURL(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_4__actItemBtn_IconURLState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_4__actItemBtn_IconURL(string serial)
        {
            Items_4__actItemBtn_IconURL((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_5__actItemBtn_IconURL(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_5__actItemBtn_IconURLState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_5__actItemBtn_IconURL(string serial)
        {
            Items_5__actItemBtn_IconURL((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_0__actItemLabel_Indirect(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_0__actItemLabel_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_0__actItemLabel_Indirect(string serial)
        {
            Items_0__actItemLabel_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_1__actItemLabel_Indirect(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_1__actItemLabel_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_1__actItemLabel_Indirect(string serial)
        {
            Items_1__actItemLabel_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_2__actItemLabel_Indirect(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_2__actItemLabel_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_2__actItemLabel_Indirect(string serial)
        {
            Items_2__actItemLabel_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_3__actItemLabel_Indirect(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_3__actItemLabel_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_3__actItemLabel_Indirect(string serial)
        {
            Items_3__actItemLabel_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_4__actItemLabel_Indirect(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_4__actItemLabel_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_4__actItemLabel_Indirect(string serial)
        {
            Items_4__actItemLabel_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_5__actItemLabel_Indirect(actItemListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_5__actItemLabel_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_5__actItemLabel_Indirect(string serial)
        {
            Items_5__actItemLabel_Indirect((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "actItemList", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            actItemBtn_PressEvent = null;
            Items_0__actItemBtn_PressEvent = null;
            Items_1__actItemBtn_PressEvent = null;
            Items_2__actItemBtn_PressEvent = null;
            Items_3__actItemBtn_PressEvent = null;
            Items_4__actItemBtn_PressEvent = null;
            Items_5__actItemBtn_PressEvent = null;
        }

        #endregion
    }
}
