//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     MicrosoftTeamsDemo
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MicrosoftTeamsDemo
{
    /// <summary>
    /// Common Interface for Root Contracts.
    /// </summary>
    public interface IContract
    {
        object UserObject { get; set; }
        void AddDevice(BasicTriListWithSmartObject device);
        void RemoveDevice(BasicTriListWithSmartObject device);

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        event EventHandler<EventArgs> Activity;
    }

    /// <summary>
    /// Root contract giving access to top level project items such as Pages and global Widgets.
    /// </summary>
    public sealed class Contract : IContract, IDisposable
    {
        #region Components

        private ComponentMediator ComponentMediator { get; set; }

        public MicrosoftTeamsDemo.home.Ihome home { get { return (MicrosoftTeamsDemo.home.Ihome)Internalhome; } }
        private MicrosoftTeamsDemo.home.home Internalhome { get; set; }

        public MicrosoftTeamsDemo.popUps.IpopUps popUps { get { return (MicrosoftTeamsDemo.popUps.IpopUps)InternalpopUps; } }
        private MicrosoftTeamsDemo.popUps.popUps InternalpopUps { get; set; }

        public MicrosoftTeamsDemo.cardSrcCameras.IcardSrcCameras cardSrcCameras { get { return (MicrosoftTeamsDemo.cardSrcCameras.IcardSrcCameras)InternalcardSrcCameras; } }
        private MicrosoftTeamsDemo.cardSrcCameras.cardSrcCameras InternalcardSrcCameras { get; set; }

        public MicrosoftTeamsDemo.IsystemFooter systemFooter { get { return (MicrosoftTeamsDemo.IsystemFooter)InternalsystemFooter; } }
        private MicrosoftTeamsDemo.systemFooter InternalsystemFooter { get; set; }

        public MicrosoftTeamsDemo.cardSourceSelectList.IcardSourceSelectList cardSourceSelectList { get { return (MicrosoftTeamsDemo.cardSourceSelectList.IcardSourceSelectList)InternalcardSourceSelectList; } }
        private MicrosoftTeamsDemo.cardSourceSelectList.cardSourceSelectList InternalcardSourceSelectList { get; set; }

        public MicrosoftTeamsDemo.IsystemHeader systemHeader { get { return (MicrosoftTeamsDemo.IsystemHeader)InternalsystemHeader; } }
        private MicrosoftTeamsDemo.systemHeader InternalsystemHeader { get; set; }

        public MicrosoftTeamsDemo.Ivolume volume { get { return (MicrosoftTeamsDemo.Ivolume)Internalvolume; } }
        private MicrosoftTeamsDemo.volume Internalvolume { get; set; }

        public MicrosoftTeamsDemo.widgetActivitiesMenu.IwidgetActivitiesMenu widgetActivitiesMenu { get { return (MicrosoftTeamsDemo.widgetActivitiesMenu.IwidgetActivitiesMenu)InternalwidgetActivitiesMenu; } }
        private MicrosoftTeamsDemo.widgetActivitiesMenu.widgetActivitiesMenu InternalwidgetActivitiesMenu { get; set; }

        public MicrosoftTeamsDemo.cardSrcATV.IcardSrcATV cardSrcATV { get { return (MicrosoftTeamsDemo.cardSrcATV.IcardSrcATV)InternalcardSrcATV; } }
        private MicrosoftTeamsDemo.cardSrcATV.cardSrcATV InternalcardSrcATV { get; set; }

        #endregion

        #region Construction and Initialization

        public Contract()
            : this(new List<BasicTriListWithSmartObject>().ToArray())
        {
        }

        public Contract(BasicTriListWithSmartObject device)
            : this(new [] { device })
        {
        }

        public Contract(BasicTriListWithSmartObject[] devices)
        {
            if (devices == null)
                throw new ArgumentNullException("Devices is null");

            ComponentMediator = new ComponentMediator();
            ComponentMediator.ConfigureActivityEvent(onActivity);

            Internalhome = new MicrosoftTeamsDemo.home.home(ComponentMediator, 3);

            InternalpopUps = new MicrosoftTeamsDemo.popUps.popUps(ComponentMediator, 18);

            InternalcardSrcCameras = new MicrosoftTeamsDemo.cardSrcCameras.cardSrcCameras(ComponentMediator, 23);

            InternalsystemFooter = new MicrosoftTeamsDemo.systemFooter(ComponentMediator, 26);

            InternalcardSourceSelectList = new MicrosoftTeamsDemo.cardSourceSelectList.cardSourceSelectList(ComponentMediator, 27);

            InternalsystemHeader = new MicrosoftTeamsDemo.systemHeader(ComponentMediator, 29);

            Internalvolume = new MicrosoftTeamsDemo.volume(ComponentMediator, 30);

            InternalwidgetActivitiesMenu = new MicrosoftTeamsDemo.widgetActivitiesMenu.widgetActivitiesMenu(ComponentMediator, 31);

            InternalcardSrcATV = new MicrosoftTeamsDemo.cardSrcATV.cardSrcATV(ComponentMediator, 33);


            for (int index = 0; index < devices.Length; index++)
            {
                AddDevice(devices[index]);
            }
        }

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        public event EventHandler<EventArgs> Activity;
        private void onActivity(GenericBase currentDevice, SmartObjectEventArgs args)
        {
            var handler = Activity;
            if (handler != null)
                handler(currentDevice, args);
        }
        #endregion

        #region Standard Contract Members

        public object UserObject { get; set; }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Internalhome.AddDevice(device);
            InternalpopUps.AddDevice(device);
            InternalcardSrcCameras.AddDevice(device);
            InternalsystemFooter.AddDevice(device);
            InternalcardSourceSelectList.AddDevice(device);
            InternalsystemHeader.AddDevice(device);
            Internalvolume.AddDevice(device);
            InternalwidgetActivitiesMenu.AddDevice(device);
            InternalcardSrcATV.AddDevice(device);

        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Internalhome.RemoveDevice(device);
            InternalpopUps.RemoveDevice(device);
            InternalcardSrcCameras.RemoveDevice(device);
            InternalsystemFooter.RemoveDevice(device);
            InternalcardSourceSelectList.RemoveDevice(device);
            InternalsystemHeader.RemoveDevice(device);
            Internalvolume.RemoveDevice(device);
            InternalwidgetActivitiesMenu.RemoveDevice(device);
            InternalcardSrcATV.RemoveDevice(device);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Internalhome.Dispose();
            InternalpopUps.Dispose();
            InternalcardSrcCameras.Dispose();
            InternalsystemFooter.Dispose();
            InternalcardSourceSelectList.Dispose();
            InternalsystemHeader.Dispose();
            Internalvolume.Dispose();
            InternalwidgetActivitiesMenu.Dispose();
            InternalcardSrcATV.Dispose();

            ComponentMediator.Dispose(); 
        }

        #endregion
    }
}

