//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     MicrosoftTeamsDemo
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MicrosoftTeamsDemo;

namespace MicrosoftTeamsDemo
{

    /// <summary>
    /// systemFooter
    /// </summary>
    public partial interface IsystemFooter 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event popUpMicsBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> popUpMicsBtn_PressEvent;

        /// <summary>
        /// Event sysHomeBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> sysHomeBtn_PressEvent;

        /// <summary>
        /// Event sysPowerBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> sysPowerBtn_PressEvent;

        /// <summary>
        /// popUpMicsBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpMicsBtn_Selected(systemFooterBoolInputSigDelegate callback);

        /// <summary>
        /// popUpMicsBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpMicsBtn_Selected(bool digital);

        /// <summary>
        /// sysHomeBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void sysHomeBtn_Selected(systemFooterBoolInputSigDelegate callback);

        /// <summary>
        /// sysHomeBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void sysHomeBtn_Selected(bool digital);

        /// <summary>
        /// sysPowerBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void sysPowerBtn_Selected(systemFooterBoolInputSigDelegate callback);

        /// <summary>
        /// sysPowerBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void sysPowerBtn_Selected(bool digital);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="systemfooter">The <see cref="IsystemFooter"/> on which to apply the feedback.</param>
    public delegate void systemFooterBoolInputSigDelegate(BoolInputSig boolInputSig, IsystemFooter systemfooter);

    /// <summary>
    /// systemFooter
    /// </summary>
    internal partial class systemFooter : IsystemFooter, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: systemFooter.popUpMicsBtn.Press
                /// popUpMicsBtn.Press
                /// </summary>
                public const uint popUpMicsBtn_PressEvent = 3;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: systemFooter.sysHomeBtn.Press
                /// sysHomeBtn.Press
                /// </summary>
                public const uint sysHomeBtn_PressEvent = 4;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: systemFooter.sysPowerBtn.Press
                /// sysPowerBtn.Press
                /// </summary>
                public const uint sysPowerBtn_PressEvent = 5;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: systemFooter.popUpMicsBtn.Selected
                /// popUpMicsBtn.Selected
                /// </summary>
                public const uint popUpMicsBtn_SelectedState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: systemFooter.sysHomeBtn.Selected
                /// sysHomeBtn.Selected
                /// </summary>
                public const uint sysHomeBtn_SelectedState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: systemFooter.sysPowerBtn.Selected
                /// sysPowerBtn.Selected
                /// </summary>
                public const uint sysPowerBtn_SelectedState = 5;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="systemFooter"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal systemFooter(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="systemFooter"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal systemFooter(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="systemFooter"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 

            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.popUpMicsBtn_PressEvent, onpopUpMicsBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.sysHomeBtn_PressEvent, onsysHomeBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.sysPowerBtn_PressEvent, onsysPowerBtn_Press);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> popUpMicsBtn_PressEvent;
        private void onpopUpMicsBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = popUpMicsBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> sysHomeBtn_PressEvent;
        private void onsysHomeBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = sysHomeBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> sysPowerBtn_PressEvent;
        private void onsysPowerBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = sysPowerBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void popUpMicsBtn_Selected(systemFooterBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpMicsBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpMicsBtn_Selected(bool digital)
        {
            popUpMicsBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void sysHomeBtn_Selected(systemFooterBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sysHomeBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void sysHomeBtn_Selected(bool digital)
        {
            sysHomeBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void sysPowerBtn_Selected(systemFooterBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sysPowerBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void sysPowerBtn_Selected(bool digital)
        {
            sysPowerBtn_Selected((sig, component) => sig.BoolValue = digital);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "systemFooter", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            popUpMicsBtn_PressEvent = null;
            sysHomeBtn_PressEvent = null;
            sysPowerBtn_PressEvent = null;
        }

        #endregion
    }
}
