//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     MicrosoftTeamsDemo
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MicrosoftTeamsDemo;

namespace MicrosoftTeamsDemo.popUpAdvRouting
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IpopUpAdvRouteSourcesByItem
    {

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<ItemEventArgs> advSrcBtn_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[0].presentItemSync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<ItemEventArgs> presentItemSync_PressEvent;

        /// <summary>
        /// popUpAdvRouteSources.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Visible(ushort listItemIndex, popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// Helper popUpAdvRouteSources.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Visible(ushort listItemIndex, bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void advSrcBtn_Selected(ushort itemIndex, popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="digital">The bool value to send to the panel.</param>
        void advSrcBtn_Selected(ushort itemIndex, bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void presentItemSync_Selected(ushort itemIndex, popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="digital">The bool value to send to the panel.</param>
        void presentItemSync_Selected(ushort itemIndex, bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void advSrcBtn_IndirectRichText(ushort itemIndex, popUpAdvRouteSourcesStringInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void advSrcBtn_IndirectRichText(ushort itemIndex, string serial);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class popUpAdvRouteSources
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public event EventHandler<ItemEventArgs> advSrcBtn_PressEvent;
        private void onadvSrcBtn_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<ItemEventArgs> handler = advSrcBtn_PressEvent;
            if (handler != null)
                handler(this, new ItemEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.ItemIndex));
        }

        /// <inheritdoc/>
        public event EventHandler<ItemEventArgs> presentItemSync_PressEvent;
        private void onpresentItemSync_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<ItemEventArgs> handler = presentItemSync_PressEvent;
            if (handler != null)
                handler(this, new ItemEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.ItemIndex));
        }

        /// <inheritdoc/>
        public void advSrcBtn_Selected(ushort itemIndex, popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_0__advSrcBtn_SelectedState + (uint) itemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void advSrcBtn_Selected(ushort itemIndex, bool digital)
        {
            advSrcBtn_Selected(itemIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void presentItemSync_Selected(ushort itemIndex, popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_0__presentItemSync_SelectedState + (uint) itemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void presentItemSync_Selected(ushort itemIndex, bool digital)
        {
            presentItemSync_Selected(itemIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteSources_List_Item1_VisibleState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, bool digital)
        {
            List_Item_Visible(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void advSrcBtn_IndirectRichText(ushort itemIndex, popUpAdvRouteSourcesStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_0__advSrcBtn_IndirectRichTextState + (uint) itemIndex * 1], this);
            }
        }

        /// <inheritdoc/>
        public void advSrcBtn_IndirectRichText(ushort itemIndex, string serial)
        {
            advSrcBtn_IndirectRichText(itemIndex, (sig, component) => sig.StringValue = serial);
        }

        #endregion
    }

    /// <summary>
    /// popUpAdvRouteSources
    /// </summary>
    public partial interface IpopUpAdvRouteSources : IpopUpAdvRouteSourcesByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_0__advSrcBtn_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[0].presentItemSync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_0__presentItemSync_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[1].advSrcBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_1__advSrcBtn_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[1].presentItemSync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_1__presentItemSync_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[2].advSrcBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_2__advSrcBtn_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[2].presentItemSync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_2__presentItemSync_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[3].advSrcBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_3__advSrcBtn_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[3].presentItemSync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_3__presentItemSync_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[4].advSrcBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_4__advSrcBtn_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[4].presentItemSync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_4__presentItemSync_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[5].advSrcBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_5__advSrcBtn_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[5].presentItemSync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_5__presentItemSync_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[6].advSrcBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_6__advSrcBtn_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[6].presentItemSync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_6__presentItemSync_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[7].advSrcBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_7__advSrcBtn_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[7].presentItemSync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_7__presentItemSync_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[8].advSrcBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_8__advSrcBtn_PressEvent;

        /// <summary>
        /// Event popUpAdvRouting.popUpAdvRouteSources.Items[8].presentItemSync.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_8__presentItemSync_PressEvent;

        /// <summary>
        /// popUpAdvRouteSources.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteSources_List_Item1_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouteSources.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteSources_List_Item1_Visible(bool digital);

        /// <summary>
        /// popUpAdvRouteSources.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteSources_List_Item2_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouteSources.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteSources_List_Item2_Visible(bool digital);

        /// <summary>
        /// popUpAdvRouteSources.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteSources_List_Item3_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouteSources.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteSources_List_Item3_Visible(bool digital);

        /// <summary>
        /// popUpAdvRouteSources.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteSources_List_Item4_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouteSources.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteSources_List_Item4_Visible(bool digital);

        /// <summary>
        /// popUpAdvRouteSources.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteSources_List_Item5_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouteSources.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteSources_List_Item5_Visible(bool digital);

        /// <summary>
        /// popUpAdvRouteSources.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteSources_List_Item6_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouteSources.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteSources_List_Item6_Visible(bool digital);

        /// <summary>
        /// popUpAdvRouteSources.List_Item7_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteSources_List_Item7_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouteSources.List_Item7_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteSources_List_Item7_Visible(bool digital);

        /// <summary>
        /// popUpAdvRouteSources.List_Item8_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteSources_List_Item8_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouteSources.List_Item8_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteSources_List_Item8_Visible(bool digital);

        /// <summary>
        /// popUpAdvRouteSources.List_Item9_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteSources_List_Item9_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouteSources.List_Item9_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteSources_List_Item9_Visible(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_0__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_0__advSrcBtn_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_0__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_0__presentItemSync_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[1].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_1__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[1].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_1__advSrcBtn_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[1].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_1__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[1].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_1__presentItemSync_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[2].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_2__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[2].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_2__advSrcBtn_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[2].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_2__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[2].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_2__presentItemSync_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[3].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_3__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[3].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_3__advSrcBtn_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[3].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_3__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[3].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_3__presentItemSync_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[4].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_4__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[4].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_4__advSrcBtn_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[4].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_4__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[4].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_4__presentItemSync_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[5].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_5__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[5].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_5__advSrcBtn_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[5].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_5__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[5].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_5__presentItemSync_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[6].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_6__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[6].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_6__advSrcBtn_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[6].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_6__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[6].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_6__presentItemSync_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[7].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_7__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[7].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_7__advSrcBtn_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[7].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_7__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[7].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_7__presentItemSync_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[8].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_8__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[8].advSrcBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_8__advSrcBtn_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[8].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_8__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[8].presentItemSync.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_8__presentItemSync_Selected(bool digital);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_0__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_0__advSrcBtn_IndirectRichText(string serial);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[1].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_1__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[1].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_1__advSrcBtn_IndirectRichText(string serial);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[2].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_2__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[2].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_2__advSrcBtn_IndirectRichText(string serial);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[3].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_3__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[3].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_3__advSrcBtn_IndirectRichText(string serial);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[4].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_4__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[4].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_4__advSrcBtn_IndirectRichText(string serial);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[5].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_5__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[5].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_5__advSrcBtn_IndirectRichText(string serial);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[6].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_6__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[6].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_6__advSrcBtn_IndirectRichText(string serial);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[7].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_7__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[7].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_7__advSrcBtn_IndirectRichText(string serial);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[8].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_8__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback);

        /// <summary>
        /// popUpAdvRouting.popUpAdvRouteSources.Items[8].advSrcBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_8__advSrcBtn_IndirectRichText(string serial);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="popupadvroutesources">The <see cref="IpopUpAdvRouteSources"/> on which to apply the feedback.</param>
    public delegate void popUpAdvRouteSourcesBoolInputSigDelegate(BoolInputSig boolInputSig, IpopUpAdvRouteSources popupadvroutesources);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="popupadvroutesources">The <see cref="IpopUpAdvRouteSources"/> on which to apply the feedback.</param>
    public delegate void popUpAdvRouteSourcesStringInputSigDelegate(StringInputSig stringInputSig, IpopUpAdvRouteSources popupadvroutesources);

    /// <summary>
    /// popUpAdvRouteSources
    /// </summary>
    internal partial class popUpAdvRouteSources : IpopUpAdvRouteSources, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion
        /// <summary>
        /// Number of Items.
        /// </summary>
        public uint ItemCount { get; private set; }

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[0].listItem_advSrcCONTRACT.advSrcBtn.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Press
                /// </summary>
                public const uint Items_0__advSrcBtn_PressEvent = 1201;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[0].listItem_advSrcCONTRACT.presentItemSync.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[0].presentItemSync.Press
                /// </summary>
                public const uint Items_0__presentItemSync_PressEvent = 1202;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[1].listItem_advSrcCONTRACT.advSrcBtn.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[1].advSrcBtn.Press
                /// </summary>
                public const uint Items_1__advSrcBtn_PressEvent = 1203;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[1].listItem_advSrcCONTRACT.presentItemSync.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[1].presentItemSync.Press
                /// </summary>
                public const uint Items_1__presentItemSync_PressEvent = 1204;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[2].listItem_advSrcCONTRACT.advSrcBtn.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[2].advSrcBtn.Press
                /// </summary>
                public const uint Items_2__advSrcBtn_PressEvent = 1205;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[2].listItem_advSrcCONTRACT.presentItemSync.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[2].presentItemSync.Press
                /// </summary>
                public const uint Items_2__presentItemSync_PressEvent = 1206;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[3].listItem_advSrcCONTRACT.advSrcBtn.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[3].advSrcBtn.Press
                /// </summary>
                public const uint Items_3__advSrcBtn_PressEvent = 1207;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[3].listItem_advSrcCONTRACT.presentItemSync.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[3].presentItemSync.Press
                /// </summary>
                public const uint Items_3__presentItemSync_PressEvent = 1208;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[4].listItem_advSrcCONTRACT.advSrcBtn.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[4].advSrcBtn.Press
                /// </summary>
                public const uint Items_4__advSrcBtn_PressEvent = 1209;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[4].listItem_advSrcCONTRACT.presentItemSync.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[4].presentItemSync.Press
                /// </summary>
                public const uint Items_4__presentItemSync_PressEvent = 1210;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[5].listItem_advSrcCONTRACT.advSrcBtn.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[5].advSrcBtn.Press
                /// </summary>
                public const uint Items_5__advSrcBtn_PressEvent = 1211;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[5].listItem_advSrcCONTRACT.presentItemSync.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[5].presentItemSync.Press
                /// </summary>
                public const uint Items_5__presentItemSync_PressEvent = 1212;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[6].listItem_advSrcCONTRACT.advSrcBtn.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[6].advSrcBtn.Press
                /// </summary>
                public const uint Items_6__advSrcBtn_PressEvent = 1213;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[6].listItem_advSrcCONTRACT.presentItemSync.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[6].presentItemSync.Press
                /// </summary>
                public const uint Items_6__presentItemSync_PressEvent = 1214;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[7].listItem_advSrcCONTRACT.advSrcBtn.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[7].advSrcBtn.Press
                /// </summary>
                public const uint Items_7__advSrcBtn_PressEvent = 1215;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[7].listItem_advSrcCONTRACT.presentItemSync.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[7].presentItemSync.Press
                /// </summary>
                public const uint Items_7__presentItemSync_PressEvent = 1216;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[8].listItem_advSrcCONTRACT.advSrcBtn.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[8].advSrcBtn.Press
                /// </summary>
                public const uint Items_8__advSrcBtn_PressEvent = 1217;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: popUpAdvRouting.popUpAdvRouteSources.Items[8].listItem_advSrcCONTRACT.presentItemSync.Press
                /// popUpAdvRouting.popUpAdvRouteSources.Items[8].presentItemSync.Press
                /// </summary>
                public const uint Items_8__presentItemSync_PressEvent = 1218;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.List_Item1_Visible
                /// popUpAdvRouteSources.List_Item1_Visible
                /// </summary>
                public const uint popUpAdvRouteSources_List_Item1_VisibleState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.List_Item2_Visible
                /// popUpAdvRouteSources.List_Item2_Visible
                /// </summary>
                public const uint popUpAdvRouteSources_List_Item2_VisibleState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.List_Item3_Visible
                /// popUpAdvRouteSources.List_Item3_Visible
                /// </summary>
                public const uint popUpAdvRouteSources_List_Item3_VisibleState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.List_Item4_Visible
                /// popUpAdvRouteSources.List_Item4_Visible
                /// </summary>
                public const uint popUpAdvRouteSources_List_Item4_VisibleState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.List_Item5_Visible
                /// popUpAdvRouteSources.List_Item5_Visible
                /// </summary>
                public const uint popUpAdvRouteSources_List_Item5_VisibleState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.List_Item6_Visible
                /// popUpAdvRouteSources.List_Item6_Visible
                /// </summary>
                public const uint popUpAdvRouteSources_List_Item6_VisibleState = 6;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.List_Item7_Visible
                /// popUpAdvRouteSources.List_Item7_Visible
                /// </summary>
                public const uint popUpAdvRouteSources_List_Item7_VisibleState = 7;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.List_Item8_Visible
                /// popUpAdvRouteSources.List_Item8_Visible
                /// </summary>
                public const uint popUpAdvRouteSources_List_Item8_VisibleState = 8;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.List_Item9_Visible
                /// popUpAdvRouteSources.List_Item9_Visible
                /// </summary>
                public const uint popUpAdvRouteSources_List_Item9_VisibleState = 9;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[0].listItem_advSrcCONTRACT.advSrcBtn.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Selected
                /// </summary>
                public const uint Items_0__advSrcBtn_SelectedState = 610;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[0].listItem_advSrcCONTRACT.presentItemSync.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[0].presentItemSync.Selected
                /// </summary>
                public const uint Items_0__presentItemSync_SelectedState = 611;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[1].listItem_advSrcCONTRACT.advSrcBtn.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[1].advSrcBtn.Selected
                /// </summary>
                public const uint Items_1__advSrcBtn_SelectedState = 612;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[1].listItem_advSrcCONTRACT.presentItemSync.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[1].presentItemSync.Selected
                /// </summary>
                public const uint Items_1__presentItemSync_SelectedState = 613;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[2].listItem_advSrcCONTRACT.advSrcBtn.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[2].advSrcBtn.Selected
                /// </summary>
                public const uint Items_2__advSrcBtn_SelectedState = 614;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[2].listItem_advSrcCONTRACT.presentItemSync.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[2].presentItemSync.Selected
                /// </summary>
                public const uint Items_2__presentItemSync_SelectedState = 615;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[3].listItem_advSrcCONTRACT.advSrcBtn.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[3].advSrcBtn.Selected
                /// </summary>
                public const uint Items_3__advSrcBtn_SelectedState = 616;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[3].listItem_advSrcCONTRACT.presentItemSync.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[3].presentItemSync.Selected
                /// </summary>
                public const uint Items_3__presentItemSync_SelectedState = 617;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[4].listItem_advSrcCONTRACT.advSrcBtn.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[4].advSrcBtn.Selected
                /// </summary>
                public const uint Items_4__advSrcBtn_SelectedState = 618;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[4].listItem_advSrcCONTRACT.presentItemSync.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[4].presentItemSync.Selected
                /// </summary>
                public const uint Items_4__presentItemSync_SelectedState = 619;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[5].listItem_advSrcCONTRACT.advSrcBtn.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[5].advSrcBtn.Selected
                /// </summary>
                public const uint Items_5__advSrcBtn_SelectedState = 620;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[5].listItem_advSrcCONTRACT.presentItemSync.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[5].presentItemSync.Selected
                /// </summary>
                public const uint Items_5__presentItemSync_SelectedState = 621;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[6].listItem_advSrcCONTRACT.advSrcBtn.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[6].advSrcBtn.Selected
                /// </summary>
                public const uint Items_6__advSrcBtn_SelectedState = 622;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[6].listItem_advSrcCONTRACT.presentItemSync.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[6].presentItemSync.Selected
                /// </summary>
                public const uint Items_6__presentItemSync_SelectedState = 623;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[7].listItem_advSrcCONTRACT.advSrcBtn.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[7].advSrcBtn.Selected
                /// </summary>
                public const uint Items_7__advSrcBtn_SelectedState = 624;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[7].listItem_advSrcCONTRACT.presentItemSync.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[7].presentItemSync.Selected
                /// </summary>
                public const uint Items_7__presentItemSync_SelectedState = 625;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[8].listItem_advSrcCONTRACT.advSrcBtn.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[8].advSrcBtn.Selected
                /// </summary>
                public const uint Items_8__advSrcBtn_SelectedState = 626;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[8].listItem_advSrcCONTRACT.presentItemSync.Selected
                /// popUpAdvRouting.popUpAdvRouteSources.Items[8].presentItemSync.Selected
                /// </summary>
                public const uint Items_8__presentItemSync_SelectedState = 627;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[0].listItem_advSrcCONTRACT.advSrcBtn.IndirectRichText
                /// popUpAdvRouting.popUpAdvRouteSources.Items[0].advSrcBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_0__advSrcBtn_IndirectRichTextState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[1].listItem_advSrcCONTRACT.advSrcBtn.IndirectRichText
                /// popUpAdvRouting.popUpAdvRouteSources.Items[1].advSrcBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_1__advSrcBtn_IndirectRichTextState = 2;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[2].listItem_advSrcCONTRACT.advSrcBtn.IndirectRichText
                /// popUpAdvRouting.popUpAdvRouteSources.Items[2].advSrcBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_2__advSrcBtn_IndirectRichTextState = 3;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[3].listItem_advSrcCONTRACT.advSrcBtn.IndirectRichText
                /// popUpAdvRouting.popUpAdvRouteSources.Items[3].advSrcBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_3__advSrcBtn_IndirectRichTextState = 4;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[4].listItem_advSrcCONTRACT.advSrcBtn.IndirectRichText
                /// popUpAdvRouting.popUpAdvRouteSources.Items[4].advSrcBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_4__advSrcBtn_IndirectRichTextState = 5;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[5].listItem_advSrcCONTRACT.advSrcBtn.IndirectRichText
                /// popUpAdvRouting.popUpAdvRouteSources.Items[5].advSrcBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_5__advSrcBtn_IndirectRichTextState = 6;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[6].listItem_advSrcCONTRACT.advSrcBtn.IndirectRichText
                /// popUpAdvRouting.popUpAdvRouteSources.Items[6].advSrcBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_6__advSrcBtn_IndirectRichTextState = 7;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[7].listItem_advSrcCONTRACT.advSrcBtn.IndirectRichText
                /// popUpAdvRouting.popUpAdvRouteSources.Items[7].advSrcBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_7__advSrcBtn_IndirectRichTextState = 8;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: popUpAdvRouting.popUpAdvRouteSources.Items[8].listItem_advSrcCONTRACT.advSrcBtn.IndirectRichText
                /// popUpAdvRouting.popUpAdvRouteSources.Items[8].advSrcBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_8__advSrcBtn_IndirectRichTextState = 9;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="popUpAdvRouteSources"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal popUpAdvRouteSources(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="popUpAdvRouteSources"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal popUpAdvRouteSources(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="popUpAdvRouteSources"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_0__advSrcBtn_PressEvent.ToString(), new Indexes(0, (ushort)Joins.Booleans.Items_0__advSrcBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_0__presentItemSync_PressEvent.ToString(), new Indexes(0, (ushort)Joins.Booleans.Items_0__presentItemSync_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_1__advSrcBtn_PressEvent.ToString(), new Indexes(1, (ushort)Joins.Booleans.Items_0__advSrcBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_1__presentItemSync_PressEvent.ToString(), new Indexes(1, (ushort)Joins.Booleans.Items_0__presentItemSync_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_2__advSrcBtn_PressEvent.ToString(), new Indexes(2, (ushort)Joins.Booleans.Items_0__advSrcBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_2__presentItemSync_PressEvent.ToString(), new Indexes(2, (ushort)Joins.Booleans.Items_0__presentItemSync_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_3__advSrcBtn_PressEvent.ToString(), new Indexes(3, (ushort)Joins.Booleans.Items_0__advSrcBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_3__presentItemSync_PressEvent.ToString(), new Indexes(3, (ushort)Joins.Booleans.Items_0__presentItemSync_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_4__advSrcBtn_PressEvent.ToString(), new Indexes(4, (ushort)Joins.Booleans.Items_0__advSrcBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_4__presentItemSync_PressEvent.ToString(), new Indexes(4, (ushort)Joins.Booleans.Items_0__presentItemSync_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_5__advSrcBtn_PressEvent.ToString(), new Indexes(5, (ushort)Joins.Booleans.Items_0__advSrcBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_5__presentItemSync_PressEvent.ToString(), new Indexes(5, (ushort)Joins.Booleans.Items_0__presentItemSync_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_6__advSrcBtn_PressEvent.ToString(), new Indexes(6, (ushort)Joins.Booleans.Items_0__advSrcBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_6__presentItemSync_PressEvent.ToString(), new Indexes(6, (ushort)Joins.Booleans.Items_0__presentItemSync_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_7__advSrcBtn_PressEvent.ToString(), new Indexes(7, (ushort)Joins.Booleans.Items_0__advSrcBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_7__presentItemSync_PressEvent.ToString(), new Indexes(7, (ushort)Joins.Booleans.Items_0__presentItemSync_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_8__advSrcBtn_PressEvent.ToString(), new Indexes(8, (ushort)Joins.Booleans.Items_0__advSrcBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_8__presentItemSync_PressEvent.ToString(), new Indexes(8, (ushort)Joins.Booleans.Items_0__presentItemSync_PressEvent, false));

            ComponentMediator.ConfigureBooleanItemEvent(controlJoinId, Joins.Booleans.Items_0__advSrcBtn_PressEvent, GetIndexes, onadvSrcBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_0__advSrcBtn_PressEvent, onItems_0__advSrcBtn_Press);
            ComponentMediator.ConfigureBooleanItemEvent(controlJoinId, Joins.Booleans.Items_0__presentItemSync_PressEvent, GetIndexes, onpresentItemSync_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_0__presentItemSync_PressEvent, onItems_0__presentItemSync_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_1__advSrcBtn_PressEvent, onItems_1__advSrcBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_1__presentItemSync_PressEvent, onItems_1__presentItemSync_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_2__advSrcBtn_PressEvent, onItems_2__advSrcBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_2__presentItemSync_PressEvent, onItems_2__presentItemSync_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_3__advSrcBtn_PressEvent, onItems_3__advSrcBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_3__presentItemSync_PressEvent, onItems_3__presentItemSync_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_4__advSrcBtn_PressEvent, onItems_4__advSrcBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_4__presentItemSync_PressEvent, onItems_4__presentItemSync_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_5__advSrcBtn_PressEvent, onItems_5__advSrcBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_5__presentItemSync_PressEvent, onItems_5__presentItemSync_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_6__advSrcBtn_PressEvent, onItems_6__advSrcBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_6__presentItemSync_PressEvent, onItems_6__presentItemSync_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_7__advSrcBtn_PressEvent, onItems_7__advSrcBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_7__presentItemSync_PressEvent, onItems_7__presentItemSync_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_8__advSrcBtn_PressEvent, onItems_8__advSrcBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_8__presentItemSync_PressEvent, onItems_8__presentItemSync_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            Indexes indexes;
            if (_indexLookup.TryGetValue(eSigType.ToString() + join.ToString(), out indexes))
            {
                return new Indexes(indexes.ItemIndex, (ushort) (join - indexes.JoinIndex), false);
            }

            return new Indexes(0, 0, true);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_0__advSrcBtn_PressEvent;
        private void onItems_0__advSrcBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_0__advSrcBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_0__presentItemSync_PressEvent;
        private void onItems_0__presentItemSync_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_0__presentItemSync_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_1__advSrcBtn_PressEvent;
        private void onItems_1__advSrcBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_1__advSrcBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_1__presentItemSync_PressEvent;
        private void onItems_1__presentItemSync_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_1__presentItemSync_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_2__advSrcBtn_PressEvent;
        private void onItems_2__advSrcBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_2__advSrcBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_2__presentItemSync_PressEvent;
        private void onItems_2__presentItemSync_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_2__presentItemSync_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_3__advSrcBtn_PressEvent;
        private void onItems_3__advSrcBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_3__advSrcBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_3__presentItemSync_PressEvent;
        private void onItems_3__presentItemSync_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_3__presentItemSync_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_4__advSrcBtn_PressEvent;
        private void onItems_4__advSrcBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_4__advSrcBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_4__presentItemSync_PressEvent;
        private void onItems_4__presentItemSync_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_4__presentItemSync_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_5__advSrcBtn_PressEvent;
        private void onItems_5__advSrcBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_5__advSrcBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_5__presentItemSync_PressEvent;
        private void onItems_5__presentItemSync_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_5__presentItemSync_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_6__advSrcBtn_PressEvent;
        private void onItems_6__advSrcBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_6__advSrcBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_6__presentItemSync_PressEvent;
        private void onItems_6__presentItemSync_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_6__presentItemSync_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_7__advSrcBtn_PressEvent;
        private void onItems_7__advSrcBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_7__advSrcBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_7__presentItemSync_PressEvent;
        private void onItems_7__presentItemSync_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_7__presentItemSync_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_8__advSrcBtn_PressEvent;
        private void onItems_8__advSrcBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_8__advSrcBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_8__presentItemSync_PressEvent;
        private void onItems_8__presentItemSync_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_8__presentItemSync_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void Items_0__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_0__advSrcBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_0__advSrcBtn_Selected(bool digital)
        {
            Items_0__advSrcBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_1__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_1__advSrcBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_1__advSrcBtn_Selected(bool digital)
        {
            Items_1__advSrcBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_2__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_2__advSrcBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_2__advSrcBtn_Selected(bool digital)
        {
            Items_2__advSrcBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_3__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_3__advSrcBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_3__advSrcBtn_Selected(bool digital)
        {
            Items_3__advSrcBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_4__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_4__advSrcBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_4__advSrcBtn_Selected(bool digital)
        {
            Items_4__advSrcBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_5__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_5__advSrcBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_5__advSrcBtn_Selected(bool digital)
        {
            Items_5__advSrcBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_6__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_6__advSrcBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_6__advSrcBtn_Selected(bool digital)
        {
            Items_6__advSrcBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_7__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_7__advSrcBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_7__advSrcBtn_Selected(bool digital)
        {
            Items_7__advSrcBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_8__advSrcBtn_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_8__advSrcBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_8__advSrcBtn_Selected(bool digital)
        {
            Items_8__advSrcBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item1_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteSources_List_Item1_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item1_Visible(bool digital)
        {
            popUpAdvRouteSources_List_Item1_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item2_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteSources_List_Item2_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item2_Visible(bool digital)
        {
            popUpAdvRouteSources_List_Item2_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item3_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteSources_List_Item3_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item3_Visible(bool digital)
        {
            popUpAdvRouteSources_List_Item3_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item4_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteSources_List_Item4_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item4_Visible(bool digital)
        {
            popUpAdvRouteSources_List_Item4_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item5_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteSources_List_Item5_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item5_Visible(bool digital)
        {
            popUpAdvRouteSources_List_Item5_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item6_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteSources_List_Item6_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item6_Visible(bool digital)
        {
            popUpAdvRouteSources_List_Item6_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item7_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteSources_List_Item7_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item7_Visible(bool digital)
        {
            popUpAdvRouteSources_List_Item7_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item8_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteSources_List_Item8_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item8_Visible(bool digital)
        {
            popUpAdvRouteSources_List_Item8_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item9_Visible(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteSources_List_Item9_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteSources_List_Item9_Visible(bool digital)
        {
            popUpAdvRouteSources_List_Item9_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_0__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_0__presentItemSync_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_0__presentItemSync_Selected(bool digital)
        {
            Items_0__presentItemSync_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_1__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_1__presentItemSync_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_1__presentItemSync_Selected(bool digital)
        {
            Items_1__presentItemSync_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_2__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_2__presentItemSync_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_2__presentItemSync_Selected(bool digital)
        {
            Items_2__presentItemSync_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_3__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_3__presentItemSync_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_3__presentItemSync_Selected(bool digital)
        {
            Items_3__presentItemSync_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_4__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_4__presentItemSync_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_4__presentItemSync_Selected(bool digital)
        {
            Items_4__presentItemSync_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_5__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_5__presentItemSync_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_5__presentItemSync_Selected(bool digital)
        {
            Items_5__presentItemSync_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_6__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_6__presentItemSync_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_6__presentItemSync_Selected(bool digital)
        {
            Items_6__presentItemSync_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_7__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_7__presentItemSync_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_7__presentItemSync_Selected(bool digital)
        {
            Items_7__presentItemSync_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_8__presentItemSync_Selected(popUpAdvRouteSourcesBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_8__presentItemSync_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_8__presentItemSync_Selected(bool digital)
        {
            Items_8__presentItemSync_Selected((sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void Items_0__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_0__advSrcBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_0__advSrcBtn_IndirectRichText(string serial)
        {
            Items_0__advSrcBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_1__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_1__advSrcBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_1__advSrcBtn_IndirectRichText(string serial)
        {
            Items_1__advSrcBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_2__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_2__advSrcBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_2__advSrcBtn_IndirectRichText(string serial)
        {
            Items_2__advSrcBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_3__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_3__advSrcBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_3__advSrcBtn_IndirectRichText(string serial)
        {
            Items_3__advSrcBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_4__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_4__advSrcBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_4__advSrcBtn_IndirectRichText(string serial)
        {
            Items_4__advSrcBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_5__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_5__advSrcBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_5__advSrcBtn_IndirectRichText(string serial)
        {
            Items_5__advSrcBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_6__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_6__advSrcBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_6__advSrcBtn_IndirectRichText(string serial)
        {
            Items_6__advSrcBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_7__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_7__advSrcBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_7__advSrcBtn_IndirectRichText(string serial)
        {
            Items_7__advSrcBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_8__advSrcBtn_IndirectRichText(popUpAdvRouteSourcesStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_8__advSrcBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_8__advSrcBtn_IndirectRichText(string serial)
        {
            Items_8__advSrcBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "popUpAdvRouteSources", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            advSrcBtn_PressEvent = null;
            Items_0__advSrcBtn_PressEvent = null;
            presentItemSync_PressEvent = null;
            Items_0__presentItemSync_PressEvent = null;
            Items_1__advSrcBtn_PressEvent = null;
            Items_1__presentItemSync_PressEvent = null;
            Items_2__advSrcBtn_PressEvent = null;
            Items_2__presentItemSync_PressEvent = null;
            Items_3__advSrcBtn_PressEvent = null;
            Items_3__presentItemSync_PressEvent = null;
            Items_4__advSrcBtn_PressEvent = null;
            Items_4__presentItemSync_PressEvent = null;
            Items_5__advSrcBtn_PressEvent = null;
            Items_5__presentItemSync_PressEvent = null;
            Items_6__advSrcBtn_PressEvent = null;
            Items_6__presentItemSync_PressEvent = null;
            Items_7__advSrcBtn_PressEvent = null;
            Items_7__presentItemSync_PressEvent = null;
            Items_8__advSrcBtn_PressEvent = null;
            Items_8__presentItemSync_PressEvent = null;
        }

        #endregion
    }
}
