//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     MicrosoftTeamsDemo
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MicrosoftTeamsDemo;

namespace MicrosoftTeamsDemo.home.popUpAdvRouting
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IpopUpAdvRouteDestByItem
    {

        /// <summary>
        /// Event home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<ItemEventArgs> advDestBtn_PressEvent;

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Visible(ushort listItemIndex, popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// Helper home.popUpAdvRouting.popUpAdvRouteDest.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Visible(ushort listItemIndex, bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void advDestBtn_Selected(ushort itemIndex, popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="digital">The bool value to send to the panel.</param>
        void advDestBtn_Selected(ushort itemIndex, bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void advDestBtn_IndirectRichText(ushort itemIndex, popUpAdvRouteDestStringInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void advDestBtn_IndirectRichText(ushort itemIndex, string serial);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class popUpAdvRouteDest
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public event EventHandler<ItemEventArgs> advDestBtn_PressEvent;
        private void onadvDestBtn_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<ItemEventArgs> handler = advDestBtn_PressEvent;
            if (handler != null)
                handler(this, new ItemEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.ItemIndex));
        }

        /// <inheritdoc/>
        public void advDestBtn_Selected(ushort itemIndex, popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_0__advDestBtn_SelectedState + (uint) itemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void advDestBtn_Selected(ushort itemIndex, bool digital)
        {
            advDestBtn_Selected(itemIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteDest_List_Item1_VisibleState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, bool digital)
        {
            List_Item_Visible(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void advDestBtn_IndirectRichText(ushort itemIndex, popUpAdvRouteDestStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_0__advDestBtn_IndirectRichTextState + (uint) itemIndex * 1], this);
            }
        }

        /// <inheritdoc/>
        public void advDestBtn_IndirectRichText(ushort itemIndex, string serial)
        {
            advDestBtn_IndirectRichText(itemIndex, (sig, component) => sig.StringValue = serial);
        }

        #endregion
    }

    /// <summary>
    /// popUpAdvRouteDest
    /// </summary>
    public partial interface IpopUpAdvRouteDest : IpopUpAdvRouteDestByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_0__advDestBtn_PressEvent;

        /// <summary>
        /// Event home.popUpAdvRouting.popUpAdvRouteDest.Items[1].advDestBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_1__advDestBtn_PressEvent;

        /// <summary>
        /// Event home.popUpAdvRouting.popUpAdvRouteDest.Items[2].advDestBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_2__advDestBtn_PressEvent;

        /// <summary>
        /// Event home.popUpAdvRouting.popUpAdvRouteDest.Items[3].advDestBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_3__advDestBtn_PressEvent;

        /// <summary>
        /// Event home.popUpAdvRouting.popUpAdvRouteDest.Items[4].advDestBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_4__advDestBtn_PressEvent;

        /// <summary>
        /// Event home.popUpAdvRouting.popUpAdvRouteDest.Items[5].advDestBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Items_5__advDestBtn_PressEvent;

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteDest_List_Item1_Visible(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteDest_List_Item1_Visible(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteDest_List_Item2_Visible(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteDest_List_Item2_Visible(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteDest_List_Item3_Visible(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteDest_List_Item3_Visible(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteDest_List_Item4_Visible(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteDest_List_Item4_Visible(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteDest_List_Item5_Visible(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteDest_List_Item5_Visible(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void popUpAdvRouteDest_List_Item6_Visible(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void popUpAdvRouteDest_List_Item6_Visible(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_0__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_0__advDestBtn_Selected(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[1].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_1__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[1].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_1__advDestBtn_Selected(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[2].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_2__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[2].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_2__advDestBtn_Selected(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[3].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_3__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[3].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_3__advDestBtn_Selected(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[4].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_4__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[4].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_4__advDestBtn_Selected(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[5].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Items_5__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[5].advDestBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Items_5__advDestBtn_Selected(bool digital);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_0__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_0__advDestBtn_IndirectRichText(string serial);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[1].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_1__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[1].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_1__advDestBtn_IndirectRichText(string serial);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[2].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_2__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[2].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_2__advDestBtn_IndirectRichText(string serial);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[3].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_3__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[3].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_3__advDestBtn_IndirectRichText(string serial);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[4].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_4__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[4].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_4__advDestBtn_IndirectRichText(string serial);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[5].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Items_5__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback);

        /// <summary>
        /// home.popUpAdvRouting.popUpAdvRouteDest.Items[5].advDestBtn.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Items_5__advDestBtn_IndirectRichText(string serial);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="popupadvroutedest">The <see cref="IpopUpAdvRouteDest"/> on which to apply the feedback.</param>
    public delegate void popUpAdvRouteDestBoolInputSigDelegate(BoolInputSig boolInputSig, IpopUpAdvRouteDest popupadvroutedest);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="popupadvroutedest">The <see cref="IpopUpAdvRouteDest"/> on which to apply the feedback.</param>
    public delegate void popUpAdvRouteDestStringInputSigDelegate(StringInputSig stringInputSig, IpopUpAdvRouteDest popupadvroutedest);

    /// <summary>
    /// popUpAdvRouteDest
    /// </summary>
    internal partial class popUpAdvRouteDest : IpopUpAdvRouteDest, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion
        /// <summary>
        /// Number of Items.
        /// </summary>
        public uint ItemCount { get; private set; }

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: home.popUpAdvRouting.popUpAdvRouteDest.Items[0].listItem_advDestCONTRACT.advDestBtn.Press
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Press
                /// </summary>
                public const uint Items_0__advDestBtn_PressEvent = 1201;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: home.popUpAdvRouting.popUpAdvRouteDest.Items[1].listItem_advDestCONTRACT.advDestBtn.Press
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[1].advDestBtn.Press
                /// </summary>
                public const uint Items_1__advDestBtn_PressEvent = 1202;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: home.popUpAdvRouting.popUpAdvRouteDest.Items[2].listItem_advDestCONTRACT.advDestBtn.Press
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[2].advDestBtn.Press
                /// </summary>
                public const uint Items_2__advDestBtn_PressEvent = 1203;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: home.popUpAdvRouting.popUpAdvRouteDest.Items[3].listItem_advDestCONTRACT.advDestBtn.Press
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[3].advDestBtn.Press
                /// </summary>
                public const uint Items_3__advDestBtn_PressEvent = 1204;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: home.popUpAdvRouting.popUpAdvRouteDest.Items[4].listItem_advDestCONTRACT.advDestBtn.Press
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[4].advDestBtn.Press
                /// </summary>
                public const uint Items_4__advDestBtn_PressEvent = 1205;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: home.popUpAdvRouting.popUpAdvRouteDest.Items[5].listItem_advDestCONTRACT.advDestBtn.Press
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[5].advDestBtn.Press
                /// </summary>
                public const uint Items_5__advDestBtn_PressEvent = 1206;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.List_Item1_Visible
                /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item1_Visible
                /// </summary>
                public const uint popUpAdvRouteDest_List_Item1_VisibleState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.List_Item2_Visible
                /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item2_Visible
                /// </summary>
                public const uint popUpAdvRouteDest_List_Item2_VisibleState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.List_Item3_Visible
                /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item3_Visible
                /// </summary>
                public const uint popUpAdvRouteDest_List_Item3_VisibleState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.List_Item4_Visible
                /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item4_Visible
                /// </summary>
                public const uint popUpAdvRouteDest_List_Item4_VisibleState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.List_Item5_Visible
                /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item5_Visible
                /// </summary>
                public const uint popUpAdvRouteDest_List_Item5_VisibleState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.List_Item6_Visible
                /// home.popUpAdvRouting.popUpAdvRouteDest.List_Item6_Visible
                /// </summary>
                public const uint popUpAdvRouteDest_List_Item6_VisibleState = 6;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[0].listItem_advDestCONTRACT.advDestBtn.Selected
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Selected
                /// </summary>
                public const uint Items_0__advDestBtn_SelectedState = 607;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[1].listItem_advDestCONTRACT.advDestBtn.Selected
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[1].advDestBtn.Selected
                /// </summary>
                public const uint Items_1__advDestBtn_SelectedState = 608;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[2].listItem_advDestCONTRACT.advDestBtn.Selected
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[2].advDestBtn.Selected
                /// </summary>
                public const uint Items_2__advDestBtn_SelectedState = 609;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[3].listItem_advDestCONTRACT.advDestBtn.Selected
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[3].advDestBtn.Selected
                /// </summary>
                public const uint Items_3__advDestBtn_SelectedState = 610;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[4].listItem_advDestCONTRACT.advDestBtn.Selected
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[4].advDestBtn.Selected
                /// </summary>
                public const uint Items_4__advDestBtn_SelectedState = 611;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[5].listItem_advDestCONTRACT.advDestBtn.Selected
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[5].advDestBtn.Selected
                /// </summary>
                public const uint Items_5__advDestBtn_SelectedState = 612;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[0].listItem_advDestCONTRACT.advDestBtn.IndirectRichText
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[0].advDestBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_0__advDestBtn_IndirectRichTextState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[1].listItem_advDestCONTRACT.advDestBtn.IndirectRichText
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[1].advDestBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_1__advDestBtn_IndirectRichTextState = 2;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[2].listItem_advDestCONTRACT.advDestBtn.IndirectRichText
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[2].advDestBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_2__advDestBtn_IndirectRichTextState = 3;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[3].listItem_advDestCONTRACT.advDestBtn.IndirectRichText
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[3].advDestBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_3__advDestBtn_IndirectRichTextState = 4;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[4].listItem_advDestCONTRACT.advDestBtn.IndirectRichText
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[4].advDestBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_4__advDestBtn_IndirectRichTextState = 5;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: home.popUpAdvRouting.popUpAdvRouteDest.Items[5].listItem_advDestCONTRACT.advDestBtn.IndirectRichText
                /// home.popUpAdvRouting.popUpAdvRouteDest.Items[5].advDestBtn.Indirect Rich Text
                /// </summary>
                public const uint Items_5__advDestBtn_IndirectRichTextState = 6;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="popUpAdvRouteDest"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal popUpAdvRouteDest(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="popUpAdvRouteDest"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal popUpAdvRouteDest(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="popUpAdvRouteDest"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_0__advDestBtn_PressEvent.ToString(), new Indexes(0, (ushort)Joins.Booleans.Items_0__advDestBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_1__advDestBtn_PressEvent.ToString(), new Indexes(1, (ushort)Joins.Booleans.Items_0__advDestBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_2__advDestBtn_PressEvent.ToString(), new Indexes(2, (ushort)Joins.Booleans.Items_0__advDestBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_3__advDestBtn_PressEvent.ToString(), new Indexes(3, (ushort)Joins.Booleans.Items_0__advDestBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_4__advDestBtn_PressEvent.ToString(), new Indexes(4, (ushort)Joins.Booleans.Items_0__advDestBtn_PressEvent, false));
            _indexLookup.Add(eSigType.Bool.ToString() + Joins.Booleans.Items_5__advDestBtn_PressEvent.ToString(), new Indexes(5, (ushort)Joins.Booleans.Items_0__advDestBtn_PressEvent, false));

            ComponentMediator.ConfigureBooleanItemEvent(controlJoinId, Joins.Booleans.Items_0__advDestBtn_PressEvent, GetIndexes, onadvDestBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_0__advDestBtn_PressEvent, onItems_0__advDestBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_1__advDestBtn_PressEvent, onItems_1__advDestBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_2__advDestBtn_PressEvent, onItems_2__advDestBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_3__advDestBtn_PressEvent, onItems_3__advDestBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_4__advDestBtn_PressEvent, onItems_4__advDestBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Items_5__advDestBtn_PressEvent, onItems_5__advDestBtn_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            Indexes indexes;
            if (_indexLookup.TryGetValue(eSigType.ToString() + join.ToString(), out indexes))
            {
                return new Indexes(indexes.ItemIndex, (ushort) (join - indexes.JoinIndex), false);
            }

            return new Indexes(0, 0, true);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_0__advDestBtn_PressEvent;
        private void onItems_0__advDestBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_0__advDestBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_1__advDestBtn_PressEvent;
        private void onItems_1__advDestBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_1__advDestBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_2__advDestBtn_PressEvent;
        private void onItems_2__advDestBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_2__advDestBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_3__advDestBtn_PressEvent;
        private void onItems_3__advDestBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_3__advDestBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_4__advDestBtn_PressEvent;
        private void onItems_4__advDestBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_4__advDestBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Items_5__advDestBtn_PressEvent;
        private void onItems_5__advDestBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Items_5__advDestBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void Items_0__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_0__advDestBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_0__advDestBtn_Selected(bool digital)
        {
            Items_0__advDestBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_1__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_1__advDestBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_1__advDestBtn_Selected(bool digital)
        {
            Items_1__advDestBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_2__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_2__advDestBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_2__advDestBtn_Selected(bool digital)
        {
            Items_2__advDestBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_3__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_3__advDestBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_3__advDestBtn_Selected(bool digital)
        {
            Items_3__advDestBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_4__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_4__advDestBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_4__advDestBtn_Selected(bool digital)
        {
            Items_4__advDestBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Items_5__advDestBtn_Selected(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Items_5__advDestBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_5__advDestBtn_Selected(bool digital)
        {
            Items_5__advDestBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item1_Visible(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteDest_List_Item1_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item1_Visible(bool digital)
        {
            popUpAdvRouteDest_List_Item1_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item2_Visible(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteDest_List_Item2_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item2_Visible(bool digital)
        {
            popUpAdvRouteDest_List_Item2_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item3_Visible(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteDest_List_Item3_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item3_Visible(bool digital)
        {
            popUpAdvRouteDest_List_Item3_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item4_Visible(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteDest_List_Item4_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item4_Visible(bool digital)
        {
            popUpAdvRouteDest_List_Item4_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item5_Visible(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteDest_List_Item5_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item5_Visible(bool digital)
        {
            popUpAdvRouteDest_List_Item5_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item6_Visible(popUpAdvRouteDestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.popUpAdvRouteDest_List_Item6_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void popUpAdvRouteDest_List_Item6_Visible(bool digital)
        {
            popUpAdvRouteDest_List_Item6_Visible((sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void Items_0__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_0__advDestBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_0__advDestBtn_IndirectRichText(string serial)
        {
            Items_0__advDestBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_1__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_1__advDestBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_1__advDestBtn_IndirectRichText(string serial)
        {
            Items_1__advDestBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_2__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_2__advDestBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_2__advDestBtn_IndirectRichText(string serial)
        {
            Items_2__advDestBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_3__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_3__advDestBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_3__advDestBtn_IndirectRichText(string serial)
        {
            Items_3__advDestBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_4__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_4__advDestBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_4__advDestBtn_IndirectRichText(string serial)
        {
            Items_4__advDestBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Items_5__advDestBtn_IndirectRichText(popUpAdvRouteDestStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Items_5__advDestBtn_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Items_5__advDestBtn_IndirectRichText(string serial)
        {
            Items_5__advDestBtn_IndirectRichText((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "popUpAdvRouteDest", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            advDestBtn_PressEvent = null;
            Items_0__advDestBtn_PressEvent = null;
            Items_1__advDestBtn_PressEvent = null;
            Items_2__advDestBtn_PressEvent = null;
            Items_3__advDestBtn_PressEvent = null;
            Items_4__advDestBtn_PressEvent = null;
            Items_5__advDestBtn_PressEvent = null;
        }

        #endregion
    }
}
