//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     MicrosoftTeamsDemo
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MicrosoftTeamsDemo;

namespace MicrosoftTeamsDemo.cardSourceSelectList
{

    /// <summary>
    /// cardSourceSelectList
    /// </summary>
    public partial interface IcardSourceSelectList 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event presentAdvRoutingBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> presentAdvRoutingBtn_PressEvent;

        /// <summary>
        /// presentAdvRoutingBtn.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void presentAdvRoutingBtn_Visibility_fb(cardSourceSelectListBoolInputSigDelegate callback);

        /// <summary>
        /// presentAdvRoutingBtn.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void presentAdvRoutingBtn_Visibility_fb(bool digital);

        /// <summary>
        /// sys.warming.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void syswarming_Visibility_fb(cardSourceSelectListBoolInputSigDelegate callback);

        /// <summary>
        /// sys.warming.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void syswarming_Visibility_fb(bool digital);

        /// <summary>
        /// sys.warmingSpinner.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void syswarmingSpinner_Visibility_fb(cardSourceSelectListBoolInputSigDelegate callback);

        /// <summary>
        /// sys.warmingSpinner.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void syswarmingSpinner_Visibility_fb(bool digital);

        /// <summary>
        /// presentAdvRoutingBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void presentAdvRoutingBtn_Selected(cardSourceSelectListBoolInputSigDelegate callback);

        /// <summary>
        /// presentAdvRoutingBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void presentAdvRoutingBtn_Selected(bool digital);

        /// <summary>
        /// ComplexComponent listItem_source
        /// </summary>
        MicrosoftTeamsDemo.cardSourceSelectList.IpresentSelectList presentSelectList { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="cardsourceselectlist">The <see cref="IcardSourceSelectList"/> on which to apply the feedback.</param>
    public delegate void cardSourceSelectListBoolInputSigDelegate(BoolInputSig boolInputSig, IcardSourceSelectList cardsourceselectlist);

    /// <summary>
    /// cardSourceSelectList
    /// </summary>
    internal partial class cardSourceSelectList : IcardSourceSelectList, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: cardSourceSelectList.presentAdvRoutingBtn.Press
                /// presentAdvRoutingBtn.Press
                /// </summary>
                public const uint presentAdvRoutingBtn_PressEvent = 2;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: cardSourceSelectList.presentAdvRoutingBtn.Visibility_fb
                /// presentAdvRoutingBtn.Visibility
                /// </summary>
                public const uint presentAdvRoutingBtn_Visibility_fbState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: cardSourceSelectList.syswarming.Visibility_fb
                /// sys.warming.Visibility
                /// </summary>
                public const uint syswarming_Visibility_fbState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: cardSourceSelectList.syswarmingSpinner.Visibility_fb
                /// sys.warmingSpinner.Visibility
                /// </summary>
                public const uint syswarmingSpinner_Visibility_fbState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: cardSourceSelectList.presentAdvRoutingBtn.Selected
                /// presentAdvRoutingBtn.Selected
                /// </summary>
                public const uint presentAdvRoutingBtn_SelectedState = 5;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="cardSourceSelectList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal cardSourceSelectList(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="cardSourceSelectList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal cardSourceSelectList(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="cardSourceSelectList"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 

            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.presentAdvRoutingBtn_PressEvent, onpresentAdvRoutingBtn_Press);
            presentSelectList = new MicrosoftTeamsDemo.cardSourceSelectList.presentSelectList(ComponentMediator, 31);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MicrosoftTeamsDemo.cardSourceSelectList.presentSelectList)presentSelectList).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MicrosoftTeamsDemo.cardSourceSelectList.presentSelectList)presentSelectList).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> presentAdvRoutingBtn_PressEvent;
        private void onpresentAdvRoutingBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = presentAdvRoutingBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void presentAdvRoutingBtn_Selected(cardSourceSelectListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.presentAdvRoutingBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void presentAdvRoutingBtn_Selected(bool digital)
        {
            presentAdvRoutingBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void presentAdvRoutingBtn_Visibility_fb(cardSourceSelectListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.presentAdvRoutingBtn_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void presentAdvRoutingBtn_Visibility_fb(bool digital)
        {
            presentAdvRoutingBtn_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void syswarming_Visibility_fb(cardSourceSelectListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.syswarming_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void syswarming_Visibility_fb(bool digital)
        {
            syswarming_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void syswarmingSpinner_Visibility_fb(cardSourceSelectListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.syswarmingSpinner_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void syswarmingSpinner_Visibility_fb(bool digital)
        {
            syswarmingSpinner_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent presentSelectList
        /// </summary>
        public MicrosoftTeamsDemo.cardSourceSelectList.IpresentSelectList presentSelectList { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "cardSourceSelectList", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            presentAdvRoutingBtn_PressEvent = null;
        }

        #endregion
    }
}
