//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.101.8.0
//     UI Plugin:   1.3701.9.0
//
//     Project:     MicrosoftTeamsDemo
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1.2
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MicrosoftTeamsDemo;

namespace MicrosoftTeamsDemo.widgetSrcCameras
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IcameraPresetListByItem
    {
        /// <summary>
        /// Fires on button list presses.  Event carries <see="IndexedButtonEventArgs"/> with ButtonIndex property (0 based).
        /// </summary>
        event EventHandler<IndexedButtonEventArgs> Button_PressEvent;

        /// <summary>
        /// Button1.Text Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void Button_Text(ushort buttonIndex, cameraPresetListStringInputSigDelegate callback);

        /// <summary>
        /// Helper Button1.Text Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Button_Text(ushort buttonIndex, string serial);

    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class cameraPresetList
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public event EventHandler<IndexedButtonEventArgs> Button_PressEvent;
        private void onButton_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<IndexedButtonEventArgs> handler = Button_PressEvent;
            if (handler != null)
                handler(this, new IndexedButtonEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.JoinIndex));
        }
                


        /// <inheritdoc/>
        public void Button_Text(ushort buttonIndex, cameraPresetListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Button_1_Button_TextState + (uint)buttonIndex * 1], this);
            }
        }

        /// <inheritdoc/>
        public void Button_Text(ushort buttonIndex, string serial)
        {
            Button_Text(buttonIndex, (sig, component) => sig.StringValue = serial);
        }

        #endregion
    }

    /// <summary>
    /// cameraPresetList
    /// </summary>
    public partial interface IcameraPresetList : IcameraPresetListByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event Button1.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_1_Button_PressEvent;

        /// <summary>
        /// Event Button2.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_2_Button_PressEvent;

        /// <summary>
        /// Event Button3.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_3_Button_PressEvent;

        /// <summary>
        /// Event Button4.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_4_Button_PressEvent;

        /// <summary>
        /// cameraPresetList.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void cameraPresetList_ListNumberOfItems(cameraPresetListUShortInputSigDelegate callback);

        /// <summary>
        /// cameraPresetList.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void cameraPresetList_ListNumberOfItems(ushort analog);

        /// <summary>
        /// cameraPresetList.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void cameraPresetList_ListNumberOfItems(short analog);

        /// <summary>
        /// Button1.Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Button_1_Button_Text(cameraPresetListStringInputSigDelegate callback);

        /// <summary>
        /// Button1.Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Button_1_Button_Text(string serial);

        /// <summary>
        /// Button2.Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Button_2_Button_Text(cameraPresetListStringInputSigDelegate callback);

        /// <summary>
        /// Button2.Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Button_2_Button_Text(string serial);

        /// <summary>
        /// Button3.Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Button_3_Button_Text(cameraPresetListStringInputSigDelegate callback);

        /// <summary>
        /// Button3.Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Button_3_Button_Text(string serial);

        /// <summary>
        /// Button4.Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Button_4_Button_Text(cameraPresetListStringInputSigDelegate callback);

        /// <summary>
        /// Button4.Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Button_4_Button_Text(string serial);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="camerapresetlist">The <see cref="IcameraPresetList"/> on which to apply the feedback.</param>
    public delegate void cameraPresetListBoolInputSigDelegate(BoolInputSig boolInputSig, IcameraPresetList camerapresetlist);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="camerapresetlist">The <see cref="IcameraPresetList"/> on which to apply the feedback.</param>
    public delegate void cameraPresetListUShortInputSigDelegate(UShortInputSig uShortInputSig, IcameraPresetList camerapresetlist);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="camerapresetlist">The <see cref="IcameraPresetList"/> on which to apply the feedback.</param>
    public delegate void cameraPresetListStringInputSigDelegate(StringInputSig stringInputSig, IcameraPresetList camerapresetlist);

    /// <summary>
    /// cameraPresetList
    /// </summary>
    internal partial class cameraPresetList : IcameraPresetList, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: widgetSrcCameras.cameraPresetList.Button1ItemPress
                /// Button1.ItemPress
                /// </summary>
                public const uint Button_1_Button_PressEvent = 1001;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: widgetSrcCameras.cameraPresetList.Button2ItemPress
                /// Button2.ItemPress
                /// </summary>
                public const uint Button_2_Button_PressEvent = 1002;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: widgetSrcCameras.cameraPresetList.Button3ItemPress
                /// Button3.ItemPress
                /// </summary>
                public const uint Button_3_Button_PressEvent = 1003;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: widgetSrcCameras.cameraPresetList.Button4ItemPress
                /// Button4.ItemPress
                /// </summary>
                public const uint Button_4_Button_PressEvent = 1004;


            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: widgetSrcCameras.cameraPresetList.ListNumberOfItems
                /// cameraPresetList.List Number Of Items
                /// </summary>
                public const uint cameraPresetList_ListNumberOfItemsState = 2;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetSrcCameras.cameraPresetList.Button1Text
                /// Button1.Text
                /// </summary>
                public const uint Button_1_Button_TextState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetSrcCameras.cameraPresetList.Button2Text
                /// Button2.Text
                /// </summary>
                public const uint Button_2_Button_TextState = 2;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetSrcCameras.cameraPresetList.Button3Text
                /// Button3.Text
                /// </summary>
                public const uint Button_3_Button_TextState = 3;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: widgetSrcCameras.cameraPresetList.Button4Text
                /// Button4.Text
                /// </summary>
                public const uint Button_4_Button_TextState = 4;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="cameraPresetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal cameraPresetList(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="cameraPresetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal cameraPresetList(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="cameraPresetList"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 

            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_1_Button_PressEvent, onButton_1_Button_Press);
            ComponentMediator.ConfigureBooleanItemEvent(controlJoinId, Joins.Booleans.Button_1_Button_PressEvent, GetIndexes, onButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_2_Button_PressEvent, onButton_2_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_3_Button_PressEvent, onButton_3_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_4_Button_PressEvent, onButton_4_Button_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            if (controlJoinId == ControlJoinId &&
                join >= Joins.Booleans.Button_1_Button_PressEvent &&
                join <= 1004)
            {
                return new Indexes(0, (ushort)(join - Joins.Booleans.Button_1_Button_PressEvent), false);
            }

            return new Indexes(0, 0, true);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_1_Button_PressEvent;
        private void onButton_1_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_1_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_2_Button_PressEvent;
        private void onButton_2_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_2_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_3_Button_PressEvent;
        private void onButton_3_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_3_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_4_Button_PressEvent;
        private void onButton_4_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_4_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }


        /// <inheritdoc/>
        public void cameraPresetList_ListNumberOfItems(cameraPresetListUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.cameraPresetList_ListNumberOfItemsState], this);
            }
        }

        /// <inheritdoc/>
        public void cameraPresetList_ListNumberOfItems(ushort analog)
        {
            cameraPresetList_ListNumberOfItems((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void cameraPresetList_ListNumberOfItems(short analog)
        {
            cameraPresetList_ListNumberOfItems((sig, component) => sig.ShortValue = analog);
        }

        /// <inheritdoc/>
        public void Button_1_Button_Text(cameraPresetListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Button_1_Button_TextState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_1_Button_Text(string serial)
        {
            Button_1_Button_Text((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Button_2_Button_Text(cameraPresetListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Button_2_Button_TextState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_2_Button_Text(string serial)
        {
            Button_2_Button_Text((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Button_3_Button_Text(cameraPresetListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Button_3_Button_TextState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_3_Button_Text(string serial)
        {
            Button_3_Button_Text((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Button_4_Button_Text(cameraPresetListStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Button_4_Button_TextState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_4_Button_Text(string serial)
        {
            Button_4_Button_Text((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "cameraPresetList", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Button_1_Button_PressEvent = null;
            Button_PressEvent = null;
            Button_2_Button_PressEvent = null;
            Button_3_Button_PressEvent = null;
            Button_4_Button_PressEvent = null;
        }

        #endregion
    }
}
